//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANYI_Cafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int uid { get; set; }
        public string uno { get; set; }
        public string uemail { get; set; }
        public string upw { get; set; }
        public string uname { get; set; }
        public Nullable<System.DateTime> ubirth { get; set; }
        public string utel { get; set; }
        public string uaddr { get; set; }
        public string urole { get; set; }
        public string uremark { get; set; }
        public bool is_valid { get; set; }
        public string verifycode { get; set; }
    }
}
